- name: CISCO IOS CATALYST RUN COMMANDS
  hosts: all
  gather_facts: True
  ignore_unreachable: yes
  tasks: 
    - name: Gather all facts
      cisco.ios.ios_facts:
        gather_subset: all
      register: facts
    - name: Display facts
      debug: 
        var: facts
    - name: Run commands on remote devices
      cisco.ios.ios_command:
        commands: 
          - show int status | i connected
          - show snmp chassis
        #wait_for: result[0] contains IOS
      register: command_output
      tags: show_command
    - name: Display output
      debug:
        msg: "{{ inventory_hostname }}, aktivnih interfacea {{ command_output.stdout_lines[0] | length }}, serijski broj {{ (command_output.stdout_lines[1] | to_nice_yaml).strip('-\n') }}"
      tags: show_command
    - name: Save command output to file
      lineinfile: 
        #state: present
        #insertafter: EOF
        #content: "{{ commands_output.stdout_lines | to_nice_yaml  }}"
        line: "{{ inventory_hostname }}, aktivnih interfacea {{ command_output.stdout_lines[0] | length }}, serijski broj {{ (command_output.stdout_lines[1] | to_nice_yaml).strip('-\n') }}"
        #marker: ""
        path: /awx-output-folder/commands_output.txt
        create: yes
      tags: show_command
#    - name: Save facts to file
#      copy: 
#        content: "{{ ansible_facts | to_nice_yaml }}"
#        dest: /awx-output-folder/{{ inventory_hostname }}-facts.txt
    - name: Config backup 
      ios_config:
        backup: True
        backup_options:
          dir_path: /awx-output-folder/
      tags: config_backup
    - name: Configure top level configuration
      cisco.ios.ios_config:
        lines: aaa authorization config-commands
        save_when: modified
      tags: configure
