- name: CISCO IOS CATALYST RUN COMMANDS
  hosts: all
  gather_facts: false
  tasks: 
    - name: Run show version on remote devices
      cisco.ios.ios_command:
        commands: 
          - show version 
          - show ip int brief 
        #wait_for: result[0] contains IOS
      register: commands_output
#    - name: Display output
#      debug:
#       var: output.stdout_lines  
    - name: Save command output to file
      copy: 
        content: "{{ commands_output.stdout_lines | to_nice_yaml  }}"
        dest: /awx-output-folder/{{ inventory_hostname }}/{{ inventory_hostname }}-commands.txt
#    - name: Save facts to file
#      copy: 
#        content: "{{ ansible_facts | to_nice_yaml }}"
#        dest: /awx-output-folder/{{ inventory_hostname }}-facts.txt
    - name: Config backup 
      ios_config:
        backup: True
        backup_options:
          dir_path: /awx-output-folder/{{ inventory_hostname }}/
