- name: CISCO IOS CATALYST RUN COMMANDS
  hosts: all
  gather_facts: false
  connection: network_cli
  vars:
    validate_certs: no
  tasks: 
    - name: Run show version on remote devices
      cisco.ios.ios_command:
        commands: show version