- name: CISCO IOS CATALYST RUN COMMANDS
  hosts: all
  gather_facts: no
  #connection: network_cli
  vars:
    validate_certs: no
  tasks: 
    - name: Run show version on remote devices
      cisco.ios.ios_command:
        commands: 
          - show version
          - show ip int brief
      register: output
    - name: Display output
      debug:
        var: output.stdout_lines 
    # - name: Save to file
    #   copy: 
    #     content: output.stdout_lines
    #     dest: /c/Users/{{ inventory_hostname }}.txt