# - name: LOCALHOST FACTS
#   hosts: localhost
#   gather_facts: yes

- name: CISCO IOS CATALYST RUN COMMANDS
  hosts: all
  gather_facts: True
  ignore_unreachable: yes
  serial: 1
  # vars:
  #   # Get current date from localhost
  #   current_datetime: "{{ hostvars['localhost'].ansible_date_time.date }}"0
  tasks: 
    - name: Gather all facts
      cisco.ios.ios_facts:
        gather_subset: all
      register: facts
      tags: facts
    - name: Display facts
      debug: 
         var: facts
      tags: facts
    - name: Run commands on remote devices
      cisco.ios.ios_command:
        commands: 
          - show pnp version | i UDI
          #- show snmp chassis
        #wait_for: result[0] contains IOS
      register: command_output_ver
      tags: show_command
    - name: Run commands on remote devices
      cisco.ios.ios_command:
        commands: 
          - show crypto pki certificates | i hex
          #- show snmp chassis
        #wait_for: result[0] contains IOS
      register: command_output_hex
      tags: show_command
    # - name: Extract text after colon
    #   debug:
    #     msg: "{{ item | map('regex_replace', '^\\s*[^:]*:\\s*', '') | list }}"
    #   loop: "{{ command_output_hex.stdout_lines }}"
    #   tags: show_command
    - name: Transform output
      set_fact:
        command_output_hex_transformed: "{{ command_output_hex.stdout_lines | flatten | map('regex_replace', '^\\s*[^:]*:\\s*', '') | list }}"
      tags: show_command
    - name: Display output
      debug:
        msg: "{{ command_output_hex_transformed.1 }}"
        #msg: "{{ ansible_net_hostname }}, aktivnih interfacea {{ command_output.stdout_lines[0] | length }}, serijski broj {{ ansible_net_serialnum }}, model {{ ansible_net_model }}, IOS {{ ansible_net_version }}"
        #msg: "{{ command_output_hex.stdout_lines | flatten }}"
      #with_items: "{{ command_output_hex.stdout_lines.0 }}"
      tags: show_command
    # - name: Save command output to file
    #   lineinfile: 
    #     #state: present
    #     #content: "{{ command_output.stdout_lines | to_nice_yaml  }}"
    #     line: "{{ inventory_hostname }}, {{ ansible_net_model }}, {{ item }}"
    #     path: /awx-output-folder/commands_output.txt
    #     create: true    
    #   with_items: "{{ command_output_hex.stdout_lines }}"         
      tags: show_command
#    - name: Save facts to file
#      copy: 
#        content: "{{ ansible_facts | to_nice_yaml }}"
#        dest: /awx-output-folder/{{ inventory_hostname }}-facts.txt
    - name: Config backup 
      ios_config:
        backup: True
        backup_options:
          dir_path: /awx-output-folder/
      tags: config_backup
    - name: Configure top level configuration
      cisco.ios.ios_config:
        lines: aaa authorization config-commands
        save_when: modified
      tags: configure
