- name: CISCO IOS CATALYST RUN COMMANDS
  hosts: all
  gather_facts: no
  #connection: network_cli
  vars:
    validate_certs: no
  tasks: 
    - name: Run show version on remote devices
      cisco.ios.ios_command:
        commands: 
          - show version | i Version
          - show ip int brief | i Vlan400
      register: output
    - name: Display output
      debug:
        var: output.stdout_lines 
    - name: Save to file
      copy: 
        content: "{{ output.stdout_lines | to_nice_yaml }}"
        dest: /awx-output-folder/{{ inventory_hostname }}.txt