- name: CISCO IOS CATALYST RUN COMMANDS
  hosts: all
  gather_facts: false
  ignore_unreachable: yes
  tasks: 
    - name: Run commands on remote devices
      cisco.ios.ios_command:
        commands: 
          - show int status | i connected
          - show snmp chassis
        #wait_for: result[0] contains IOS
      register: commands_output
      tags: show_command
    - name: Display output
      debug:
       var: commands_output  
      tags: show_command
    - name: Save command output to file
      copy: 
        content: "{{ commands_output.stdout_lines | to_nice_yaml  }}"
        dest: /awx-output-folder/{{ inventory_hostname }}/{{ inventory_hostname }}-commands.txt
      tags: show_command
#    - name: Save facts to file
#      copy: 
#        content: "{{ ansible_facts | to_nice_yaml }}"
#        dest: /awx-output-folder/{{ inventory_hostname }}-facts.txt
    - name: Config backup 
      ios_config:
        backup: True
        backup_options:
          dir_path: /awx-output-folder/
      tags: config_backup
    - name: Configure top level configuration
      cisco.ios.ios_config:
        lines: aaa authorization config-commands
        save_when: modified
      tags: configure
