- name: CISCO IOS CATALYST RUN COMMANDS
  hosts: all
  gather_facts: no
  #connection: network_cli
  vars:
    validate_certs: no
  tasks: 
    - name: Run show version on remote devices
      cisco.ios.ios_command:
        commands: 
          - show version 
          - show ip int brief 
        #wait_for: result[0] contains IOS
      register: output
#    - name: Display output
#      debug:
#       var: output.stdout_lines 
    - name: Current date_time
      debug:
        var: ansible_date_time
    - name: Save to file
      copy: 
        content: "{{ output.stdout_lines | to_nice_yaml  }}"
        dest: /awx-output-folder/{{ inventory_hostname }}-{{ ansible_date_time.iso8601 }}.txt